### ISSUE TITLE
Support any fields in comments, not just example

### ISSUE THREAD

**Issue by matryer** [pacedotdev/oto#12]
```
// This is a comment.
// example: "Hi there"
// required: true
// monkey: "Hell yes"
```

**Comment by sethcenterbar** [comment]
I'd love to take a stab at this as my first open-source contribution. It looks like it would require changes to the parseField and extractExample functions, possibly more. I imagine we should update extractExample to something more generic. 

I need a bit of time to familiarize myself with the project. Please let me know if there are any gotcha's you can think of that I should consider.

**Comment by matryer** [comment]
That's great @sethcenterbar.

I think there should be a new function called something like `extractCommentMetadata` or similar that puts the special comments into a `map[string]interface{}`. This should be easy to unit test, and can be done before we then work on integrating it into the wider project.

How does that sound?
