### ISSUE TITLE
Autogenerated documentation doesn't handle special characters properly

### ISSUE THREAD

**Issue by jimen0** [pacedotdev/oto#17]
Oto's autogenerated documentation doesn't properly encode special characters such as double quotes. I found this problem while reading pace's docs and reproduced it by myself. You can find an example here:

- Service definition with double quoted text: https://github.com/pacedotdev/pace/blob/d241b53b81fa4d2457bab150a66442263587298b/oto/cards.go#L50-L52 (left browser)
- Generated Go code with encoded double quotes: https://github.com/pacedotdev/pace/blob/d241b53b81fa4d2457bab150a66442263587298b/pace.gen.go#L743-L745 (right browser)

![image](https://user-images.githubusercontent.com/6826244/90988067-265e7f80-e590-11ea-8621-c0eef3929ff0.png)

- Docs as displayed on `pkg.go.dev`: https://pkg.go.dev/github.com/pacedotdev/pace?tab=doc#AddCommentRequest

![image](https://user-images.githubusercontent.com/6826244/90988082-43934e00-e590-11ea-94c2-847071404f24.png)

Please, feel free to close this issue if this is the intended behavior. I was just trying the tool and noticed it.

Best,
Miguel

**Comment by matryer** [comment]
Infuriating, thanks for reporting @jimen0.

**Comment by simonjanss** [comment]
This comes from the plush-package, example:

```go
ctx := plush.NewContext()
ctx.Set("search", "tag:'simon'")
text, _ := plush.Render("<%= search %>", ctx)
fmt.Println("output:", text)
// output: tag:&#39;simon&#39

**Comment by matryer** [comment]
Oh so maybe if I change the type to `template.HTML` it will work. I know Plush respects that.

**Comment by matryer** [comment]
@jimen0 @simonjanss Thank you - this is much better now that people don't need to learn unicode to read the docs :)

**Comment by simonjanss** [comment]
> @jimen0 @simonjanss Thank you - this is much better now that people don't need to learn unicode to read the docs :)

My pleasure, thank you for a great tool!
