### ISSUE TITLE
Byte slice type not handled

### ISSUE THREAD

**Issue by TcM1911** [pacedotdev/oto#19]
The parser doesn't handle `byte` and `[]byte` types when parsing the JSType. This will cause the generated code to have a type of `[]` if it is a `[]byte`. According to the JSON encoding documentation, `[]byte` types are base64 encoded to a string. The proper JSType should be a `string`.

This can be handled in the template by checking if the "go type" is of `byte` and that it is a multiple. This snippet can handle the case:
```
<%= for (object) in def.Objects { %>
<%= format_comment_text(object.Comment) %>export interface <%= object.Name %> {
<%= for (field) in object.Fields { %>
        <%= format_comment_text(field.Comment) %>       <%= field.NameLowerCamel %>: <%= if (field.Type.IsObject) { %><%= field.Type.TypeName %><% } else if (field.Type.TypeName == "byte" && field.Type.Multiple) { %>string<% } else { %><%= field.Type.JSType %><% } %><%= if (field.Type.Multiple && field.Type.TypeName != "byte") { %>[]<% } %>;
<% } %>
}
<% } %>
```

The cleaner way to handle this would be to do it in the parser but I couldn't find a nice way to do it with a major redesign. It would need to the determination between single and multi-type as it's parsing the JSType.

**Comment by matryer** [comment]
@TcM1911 Why would you prefer `[]byte` over `string`? Is there an advantage to using a slice of bytes in the request/response objects?

**Comment by TcM1911** [comment]
@matryer, `[]byte` can handle binary data. For example, upload/download an image.

**Comment by TcM1911** [comment]
Also, it would have a similar behaviour as protobuf's type mapping: https://developers.google.com/protocol-buffers/docs/proto3#json.

**Comment by matryer** [comment]
I wouldn't use JSON to do this tbh. In Pace, we have special endpoints for binary data. You _could_ base64 encode it, which would probably be safer, but then you'd use a `string`.

@dahernan Thoughts?

**Comment by matryer** [comment]
We did have a solution for this in a previous design of this, and tbh, it was so ugly, I think it put us off.

**Comment by dahernan** [comment]
Yeah, in the past when we had to handle binary data we had two cases:

* Very small, so you handle as a string and do the base64 encoding yourself at service level.
* Large (or need it to be scalable), and that goes to different path like cloud storage.

So we prefer to not implemented, and make you think hehehe

**Comment by TcM1911** [comment]
Fair. For my use case, I can handle it in the template so it's not an issue. I'm closing this request.
