### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by fr3fou** [pacedotdev/oto#21]
Is defining a validation schema beyond the scope of oto or is it something that's planned? (thinking something along the lines of swagger)

**Comment by matryer** [comment]
@fr3fou we added 'metadata' to comments, and this could be used for validation. E.g.  You could say `required: true` and then modify the template to check for that field to do extra work after decoding.

People will solve this in different ways, so it doesn't feel like it would go into Oto explicitly. @dahernan What do you think?

**Comment by dahernan** [comment]
agree, validation is out of the scope for now

**Comment by fr3fou** [comment]
What about having "recipes" that show common practices / examples of how to achieve similar things?

**Comment by matryer** [comment]
@fr3fou I'd be happy to link to any blog posts etc. And might consider writing some myself too. We're trying to balance providing the core of a capability without it growing into an opinionated framework.

**Comment by matryer** [comment]
Closing. Thank you.

**Comment by fr3fou** [comment]
Sorry for necro-ing, but are there any blog posts for this yet?
