### ISSUE TITLE
Copy struct tags to generated server.go

### ISSUE THREAD

**Issue by nachtjasmin** [pacedotdev/oto#31]
When defining additional struct tags, like the ones from the [go-playground/validator](https://github.com/go-playground/validator) package, they aren't copied to the generated `oto.gen.go` file. I could define them again or do some other type of validation in the implementation, but I think this is a nice and clean way for things like that.

**Comment by dahernan** [comment]
I believe we support that.
Check this:
https://github.com/pacedotdev/oto/pull/8

**Comment by nachtjasmin** [comment]
Ah, thanks! I just used the default template, but editing the template is easy :)

And while I’m here at it: good job with Oto in general, it’s really easy to use compared to gRPC. 😄
