### ISSUE TITLE
[question] How should errors be handled?

### ISSUE THREAD

**Issue by nachtjasmin** [pacedotdev/oto#32]
So, oto generates an error property with each response. Should I set this manually, or doing the go way? So, what of these approaches is better:

```go
// this:
	if err != nil {
		return &MyServiceResponse{Error: "not found"}, nil
	}

// or this?
	if err != nil {
		return nil, errors.New("not found")
	}
```

**Comment by dahernan** [comment]
Is more up to you and the style that you use given the type of error.

For example in Pace, we choose first one for application error, for example validation error.
And second is like a system error, for example can not connect to the database.

**Comment by nachtjasmin** [comment]
Thanks, thought that you use it like this, but wanted some clarification to be sure. Then I will do it similar 🙂
