### ISSUE TITLE
/oto/ path shouldn't be hard-coded in otohttp

### ISSUE THREAD

**Issue by curio77** [pacedotdev/oto#9]
The oto API base path can be adjusted in principle via the JS template and through the Go-side server setup.  However, `/oto/` is also hardcoded at one location in `otohttp`: https://github.com/pacedotdev/oto/blob/650a128de998ceb63eb8e000578ccf06321eb71c/otohttp/server.go#L45

If that was made configurable, users would be able to use a different base path (which is currently impossible without forking the project).

**Comment by matryer** [comment]
@curio77 Agreed. Would you like to suggest a solution?

**Comment by curio77** [comment]
Parameterize the `Server` constructor for the path prefix (either directly or via a config struct).  Or make that path prefix an optional path formatting function that yields the entire path given the service and method.  That's more flexible in case anyone wants to customize things to a greater extent, but probably unnecessary.  Maybe implement either via a separate constructor to avoid breaking backwards compatibility by changing the existing one's signature.

Do you want a PR for either, or is there an approach that's more in line with the bigger vision you may have? :smiley:
